baseURL = "/"
languageCode = "en-us"
title = "SuperCopyCoder"
theme = "custom-theme"

# Pagination
[pagination]
pagerSize = 10
path = "page"

# SEO and Markup
enableRobotsTXT = true
enableGitInfo = true

# RSS Configuration
[params.rss]
  limit = 20
  fullContent = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4

# SEO Configuration
[params]
  description = "模仿，是最好的致敬。站在巨人的肩膀，站得更高 - SuperCopyCoder"
  keywords = ["SuperCopyCoder", "编程", "代码", "模仿", "学习", "开发"]
  author = "SuperCopyCoder"
  images = ["/images/og-image.png"]
  
  # Social Media
  twitter = "@yourusername"
  facebook = "yourfacebookpage"
  
  # Monetag Integration
  monetag_enabled = true
  monetag_site_id = "YOUR_MONETAG_SITE_ID"
  
  # Search Configuration
  search_enabled = true
  
  # Likes Configuration
  likes_enabled = true
  likes_storage = "localStorage" # or "api" for server-side storage

# Menu Configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Claude资源中心"
    url = "https://claude.supercopycoder.xyz/"
    weight = 50
  [[menu.main]]
    name = "Claude Code新手入门"
    url = "/posts/claude-code-newbie-guide-2025-09-09/"
    weight = 51

# SEO and Social
[params.seo]
  enable = true
  title_separator = " | "
  
[params.social]
  twitter = "yourusername"
  facebook = "yourfacebookpage"
  linkedin = "yourlinkedinprofile"

# Output formats
disableKinds = ["RSS"]
[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true