baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "SuperCopyCoder - Development"
theme = "custom-theme"

# Pagination
[pagination]
pagerSize = 10
path = "page"

# SEO and Markup
enableRobotsTXT = false  # Disable robots.txt in development
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4

# SEO Configuration
[params]
  description = "Development version - 模仿，是最好的致敬。站在巨人的肩膀，站得更高 - SuperCopyCoder"
  keywords = ["SuperCopyCoder", "编程", "代码", "模仿", "学习", "开发", "development"]
  author = "SuperCopyCoder"
  images = ["/images/og-image.png"]
  
  # Social Media
  twitter = "@yourusername"
  facebook = "yourfacebookpage"
  
  # Monetag Integration - Disable in development
  monetag_enabled = false
  monetag_site_id = ""
  
  # Search Configuration
  search_enabled = true
  
  # Likes Configuration
  likes_enabled = true
  likes_storage = "localStorage"

# Menu Configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
  [[menu.main]]
    name = "Claude资源中心"
    url = "https://claude.supercopycoder.xyz/"
    weight = 50

# SEO and Social
[params.seo]
  enable = true
  title_separator = " | "
  
[params.social]
  twitter = "yourusername"
  facebook = "yourfacebookpage"
  linkedin = "yourlinkedinprofile"

# Output formats for search
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true
    notAlternative = true