name: Daily Claude Prompts Analysis

on:
  schedule:
    # 每天北京时间12:00运行（UTC 04:00）
    - cron: '0 4 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  analyze-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许写仓库内容
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      timeout-minutes: 10
      run: |
        echo "📦 安装 Python 依赖..."
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        echo "✅ 依赖安装完成"

    - name: Check Python syntax
      run: |
        echo "🔍 检查Python语法..."
        python scripts/check-syntax.py

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Run Claude prompts analyzer
      id: analyzer
      timeout-minutes: 30
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTIONS: true
        DAYS_BACK: 7
        MAX_PROJECTS: 3
      run: |
        echo "🚀 开始运行Claude Code Prompts分析器..."
        cd ${{ github.workspace }}
        if ! python scripts/claude_prompts_analyzer.py; then
          echo "❌ 分析器运行失败，请检查日志"
          echo "analyzer_success=false" >> $GITHUB_OUTPUT
        else
          echo "✅ 分析器运行成功"
          echo "analyzer_success=true" >> $GITHUB_OUTPUT
        fi

    - name: Check for new articles
      id: check_articles
      run: |
        NEW_ARTICLES=$(find content/posts -name "*claude-prompts*$(date +%Y-%m-%d)*" -type f | wc -l)
        echo "new_articles=$NEW_ARTICLES" >> $GITHUB_OUTPUT
        echo "Found $NEW_ARTICLES new Claude prompts articles for today"

    - name: Build Hugo site
      if: steps.check_articles.outputs.new_articles > 0
      timeout-minutes: 10
      run: |
        echo "🏗️ 构建 Hugo 站点..."
        hugo --cleanDestinationDir --minify
        echo "✅ 站点构建完成"

    - name: Commit and push changes
      if: steps.check_articles.outputs.new_articles > 0
      run: |
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "🤖 Auto: Daily Claude prompts analysis $(date +%Y-%m-%d) - ${{ steps.check_articles.outputs.new_articles }} articles"
          git push
        else
          echo "No changes to commit"
        fi

    - name: Create summary
      if: always()
      run: |
        echo "## 📊 Daily Claude Prompts Analysis Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date +%Y-%m-%d)" >> $GITHUB_STEP_SUMMARY
        echo "- **New Articles**: ${{ steps.check_articles.outputs.new_articles }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Analyzer Status**: ${{ steps.analyzer.outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Overall Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.check_articles.outputs.new_articles }}" -gt 0 ]; then
          echo "- **Result**: ✅ Successfully generated and published" >> $GITHUB_STEP_SUMMARY
          echo "### 📄 Generated Articles:" >> $GITHUB_STEP_SUMMARY
          find content/posts -name "*claude-prompts*$(date +%Y-%m-%d)*" -type f -exec basename {} \; | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Result**: ℹ️ No new Claude prompts articles generated today" >> $GITHUB_STEP_SUMMARY
        fi
        
        # 显示历史统计
        if [ -f "data/claude_prompts_projects.json" ]; then
          TOTAL_PROJECTS=$(python3 -c "import json; print(json.load(open('data/claude_prompts_projects.json'))['total_projects'])" 2>/dev/null || echo "0")
          echo "- **Total Analyzed Claude Prompts Projects**: $TOTAL_PROJECTS" >> $GITHUB_STEP_SUMMARY
        fi